'''Constants for the Glue Job'''

AWS_REGION              = 'eu-west-1'
AWS_BUCKET              = 'stg-dlk-sbx-ds-9-raw'
AWS_FOLDER              = 'events_feed/events_jsonl/'
AWS_ATHENA_DATABASE     = 'stg-dlk-sbx-ds9-raw-db'
AWS_ATHENA_OUPUT        = 's3://stg-dlk-sbx-ds-9-raw'
AWS_PROFILE             = ''
AWS_SECRET_NAME         = 'stg/dlk/sapcdc/ds9/secrets'
S3_DESTINATION_BUCKET   = 'stg-dlk-sbx-ds-9-raw'
S3_DESTINATION_PATH     = 'sapcdc_feed/audit_search_jsonl_gzip/'
S3_PROCESSED_FOLDER     = 'sapcdc_feed_processed/'
SNS_FAILURE_TOPIC       = 'arn:aws:sns:eu-west-1:816247855850:ds9-failure-topic'
SQL_QUERIES_BUCKET      = 'stg-dlk-sbx-code-artifacts'
SQL_QUERIES_FOLDER      = 'artifacts/glue_job_ds9/sql/'
