'''Constants for the Glue Job'''

# AWS_SECRET_NAME       = 'glue_job_sftp_data_catalog'
# S3_DESTINATION_BUCKET = 'stg-dlk-sbx-ds-11-raw'
# S3_DESTINATION_PATH = 'events_feed/events_jsonl_gzip/'
# S3_PROCESSED_FOLDER = 'events_feed_processed/'

AWS_REGION              = 'eu-west-1'
# AWS_BUCKET              = 'stg-dlk-sbx-code-artifacts'
# AWS_FOLDER              = 'artifacts/glue_job_ds8/sql/'
AWS_SECRET_NAME         = 'stg/dlk/docebo/ds6/secrets'
# AWS_ATHENA_DATABASE     = 'stg-dlk-sbx-ds8-raw-db'
# AWS_ATHENA_OUPUT        = 's3://stg-dlk-sbx-ds-8-raw'
# AWS_PROFILE             = ''
# FTP_FOLDER              = '/data/feed'
# FTP_FILE_PATTERN        = 'products_feed_*.gz'
# S3_BUCKET               = 'stg-dlk-sbx-ds-8-raw'
# S3_PATH                 = 'products_feed/products_jsonl_gzip/'
